language: erlang

env:
  - LUAROCKS_VERSION="2.1.2"

branches:
  only:
    - master

install:
  - sudo apt-get install lua5.2
  - sudo apt-get install lua5.2-dev
  - wget http://luarocks.org/releases/luarocks-${LUAROCKS_VERSION}.tar.gz
  - tar zxvpf luarocks-${LUAROCKS_VERSION}.tar.gz
  - cd luarocks-${LUAROCKS_VERSION}
  - ./configure --prefix=${HOME} --lua-version=5.2 --with-lua-include="/usr/include/lua5.2"
  - make bootstrap
  - cd ..
  - export PATH=${PATH}:${HOME}/bin
  - luarocks install serpent
  - luarocks install luafilesystem
  - luarocks install dkjson
  - luarocks install lualogging
  - luarocks install lua_cliargs
  - luarocks build rocks/lpack-master-1.rockspec
  - luarocks build rocks/lua-websockets-master-1.rockspec
  - luarocks build rocks/lua-ev-master-1.rockspec
  - export $(luarocks path | tr "'" ";")

script:
  - ./bin/make-test
  - ./bin/make-check

notifications:
  recipients:
    - alban.linard@lsv.ens-cachan.fr
  email:
    on_success: change
    on_failure: always
